import type { BuiltinCategoryId, Category, CategoryRule } from './types'

export const CATEGORIES: Category[] = [
  { id: 'groceries', label: 'Groceries', color: '#22c55e' },
  { id: 'coffee_restaurants', label: 'Coffee & Restaurants', color: '#f97316' },
  { id: 'rent', label: 'Rent', color: '#8b5cf6' },
  { id: 'clothing', label: 'Clothing', color: '#ec4899' },
  { id: 'transport', label: 'Transport', color: '#3b82f6' },
  { id: 'subscriptions', label: 'Subscriptions', color: '#06b6d4' },
  { id: 'insurance', label: 'Insurance', color: '#64748b' },
  { id: 'health', label: 'Health', color: '#14b8a6' },
  { id: 'utilities', label: 'Utilities', color: '#eab308' },
  { id: 'shopping', label: 'Shopping', color: '#a855f7' },
  { id: 'gifts', label: 'Gifts', color: '#db2777' },
  { id: 'entertainment', label: 'Entertainment', color: '#f43f5e' },
  { id: 'hobbies', label: 'Hobbies', color: '#84cc16' },
  { id: 'kids', label: 'Kids', color: '#f59e0b' },
  { id: 'travel', label: 'Travel', color: '#0ea5e9' },
  { id: 'reserves', label: 'Reserves (Rücklagen)', color: '#7c3aed' },
  {
    id: 'investments',
    label: 'Investments (dividends)',
    color: '#059669',
    isIncome: true,
  },
  {
    id: 'securities',
    label: 'Securities (buys/sells)',
    color: '#0f766e',
    excludeFromTotals: true,
  },
  { id: 'atm', label: 'ATM / Cash', color: '#78716c' },
  { id: 'salary', label: 'Salary', color: '#10b981', isIncome: true },
  {
    id: 'excluded',
    label: 'Excluded',
    color: '#a1a1aa',
    excludeFromTotals: true,
  },
  { id: 'other', label: 'Other', color: '#6b7280' },
  { id: 'uncategorized', label: 'Uncategorized', color: '#d1d5db' },
]

export const CATEGORY_MAP: Record<BuiltinCategoryId, Category> = Object.fromEntries(
  CATEGORIES.map((c) => [c.id, c]),
) as Record<BuiltinCategoryId, Category>

function rule(
  id: string,
  categoryId: BuiltinCategoryId,
  pattern: string,
  isRegex = false,
): CategoryRule {
  return { id, categoryId, pattern, isRegex, source: 'default' }
}

/** Default German merchant / keyword rules. First match wins (order matters). */
export const DEFAULT_RULES: CategoryRule[] = [
  // Securities trades (buys/sells) — exclude from household spend
  rule('sec1', 'securities', 'buy trade', false),
  rule('sec2', 'securities', 'sell trade', false),
  rule('sec3', 'securities', 'savings plan execution', false),
  rule('sec4', 'securities', 'wertpapierkauf', false),
  rule('sec5', 'securities', 'wertpapierverkauf', false),
  rule('sec6', 'securities', 'wertpapierabrechnung', false),
  rule('sec7', 'securities', 'wertpapiergeschäft', false),
  rule('sec8', 'securities', 'warrant exercise', false),
  rule('sec9', 'securities', 'ipo access', false),
  rule('sec10', 'securities', 'ipo subscription', false),
  rule('sec11', 'securities', ' · buy · ', false),
  rule('sec12', 'securities', ' · sell · ', false),
  rule('sec13', 'securities', '· trading', false),

  // Own-account / savings movements — exclude from household totals
  rule('t1', 'excluded', 'sparkonto', false),
  rule('t2', 'excluded', 'tagesgeld', false),
  rule('t3', 'excluded', 'eigenüberweisung', false),
  rule('t4', 'excluded', 'umbuchung', false),
  rule('t5', 'excluded', 'depot', false),

  // Salary (avoid bare "abrechnung" — matches Kreditkartenabrechnung etc.)
  rule('s1', 'salary', 'gehalt', false),
  rule('s2', 'salary', 'lohn', false),
  rule('s3', 'salary', 'salary', false),
  rule('s4', 'salary', 'gehaltsabrechnung', false),
  rule('s5', 'salary', 'lohnabrechnung', false),

  // Rent
  rule('r1', 'rent', 'miete', false),
  rule('r2', 'rent', 'kaltmiete', false),
  rule('r3', 'rent', 'warmmiete', false),
  rule('r4', 'rent', 'wohnungsgesellschaft', false),

  // Groceries
  rule('g1', 'groceries', 'rewe', false),
  rule('g2', 'groceries', 'edeka', false),
  rule('g3', 'groceries', 'lidl', false),
  rule('g4', 'groceries', 'aldi', false),
  rule('g5', 'groceries', 'penny', false),
  rule('g6', 'groceries', 'netto', false),
  rule('g7', 'groceries', 'kaufland', false),
  rule('g8', 'groceries', 'dm-drogerie', false),
  rule('g9', 'groceries', 'dm ', false),
  rule('g10', 'groceries', 'rossmann', false),
  rule('g11', 'groceries', 'budni', false),
  rule('g12', 'groceries', 'bio company', false),
  rule('g13', 'groceries', 'alnatura', false),
  rule('g14', 'groceries', 'getränke', false),

  // Coffee & restaurants
  rule('c1', 'coffee_restaurants', 'starbucks', false),
  rule('c2', 'coffee_restaurants', 'coffee fellows', false),
  rule('c3', 'coffee_restaurants', 'barista', false),
  rule('c4', 'coffee_restaurants', 'café', false),
  rule('c5', 'coffee_restaurants', 'cafe ', false),
  rule('c6', 'coffee_restaurants', 'mcdonald', false),
  rule('c7', 'coffee_restaurants', 'burger king', false),
  rule('c8', 'coffee_restaurants', 'subway', false),
  rule('c9', 'coffee_restaurants', 'deliveroo', false),
  rule('c10', 'coffee_restaurants', 'lieferando', false),
  rule('c11', 'coffee_restaurants', 'uber eats', false),
  rule('c12', 'coffee_restaurants', 'wolt', false),
  rule('c13', 'coffee_restaurants', 'restaurant', false),
  rule('c14', 'coffee_restaurants', 'backwerk', false),
  rule('c15', 'coffee_restaurants', 'backfactory', false),
  rule('c16', 'coffee_restaurants', 'pret a manger', false),

  // Transport
  rule('tr1', 'transport', 'bvg', false),
  rule('tr2', 'transport', 'deutsche bahn', false),
  rule('tr3', 'transport', 'db vertrieb', false),
  rule('tr4', 'transport', 'db fernverkehr', false),
  rule('tr5', 'transport', 'flixbus', false),
  rule('tr6', 'transport', 'flixtrain', false),
  rule('tr7', 'transport', 'uber', false),
  rule('tr8', 'transport', 'bolt', false),
  rule('tr9', 'transport', 'free now', false),
  rule('tr10', 'transport', 'taxi', false),
  rule('tr11', 'transport', 'shell', false),
  rule('tr12', 'transport', 'aral', false),
  rule('tr13', 'transport', 'jet tankstelle', false),
  rule('tr14', 'transport', 'tankstelle', false),
  rule('tr15', 'transport', 'clevershuttle', false),
  rule('tr16', 'transport', 'nextbike', false),
  rule('tr17', 'transport', 'lime ', false),
  rule('tr18', 'transport', 'tier ', false),

  // Clothing
  rule('cl1', 'clothing', 'h&m', false),
  rule('cl2', 'clothing', 'zara', false),
  rule('cl3', 'clothing', 'uniqlo', false),
  rule('cl4', 'clothing', 'c&a', false),
  rule('cl5', 'clothing', 'about you', false),
  rule('cl6', 'clothing', 'zalando', false),
  rule('cl7', 'clothing', 'asos', false),
  rule('cl8', 'clothing', 'primark', false),
  rule('cl9', 'clothing', 'peek & cloppenburg', false),
  rule('cl10', 'clothing', 'snipes', false),
  rule('cl11', 'clothing', 'adidas', false),
  rule('cl12', 'clothing', 'nike', false),

  // Subscriptions
  rule('sub1', 'subscriptions', 'netflix', false),
  rule('sub2', 'subscriptions', 'spotify', false),
  rule('sub3', 'subscriptions', 'disney', false),
  rule('sub4', 'subscriptions', 'amazon prime', false),
  rule('sub5', 'subscriptions', 'apple.com/bill', false),
  rule('sub6', 'subscriptions', 'google *', false),
  rule('sub7', 'subscriptions', 'youtube', false),
  rule('sub8', 'subscriptions', 'adobe', false),
  rule('sub9', 'subscriptions', 'microsoft', false),
  rule('sub10', 'subscriptions', 'github', false),
  rule('sub11', 'subscriptions', 'openai', false),
  rule('sub12', 'subscriptions', 'chatgpt', false),
  rule('sub13', 'subscriptions', 'icloud', false),
  rule('sub14', 'subscriptions', 'dropbox', false),
  rule('sub15', 'subscriptions', '1password', false),
  rule('sub16', 'subscriptions', 'nordvpn', false),
  rule('sub17', 'subscriptions', 'fitness', false),
  rule('sub18', 'subscriptions', 'fitnessstudio', false),
  rule('sub19', 'subscriptions', 'mcfit', false),
  rule('sub20', 'subscriptions', 'urban sports', false),

  // Insurance
  rule('i1', 'insurance', 'versicherung', false),
  rule('i2', 'insurance', 'allianz', false),
  rule('i3', 'insurance', 'huk', false),
  rule('i4', 'insurance', 'axa', false),
  rule('i5', 'insurance', 'ergo', false),
  rule('i6', 'insurance', 'devk', false),
  rule('i7', 'insurance', 'krankenkasse', false),
  rule('i8', 'insurance', 'aok', false),
  rule('i9', 'insurance', 'tk-', false),
  rule('i10', 'insurance', 'techniker', false),
  rule('i11', 'insurance', 'barmer', false),
  rule('i12', 'insurance', 'dak-', false),

  // Health
  rule('h1', 'health', 'apotheke', false),
  rule('h2', 'health', 'pharmacy', false),
  rule('h3', 'health', 'arzt', false),
  rule('h4', 'health', 'zahnarzt', false),
  rule('h5', 'health', 'docmorris', false),
  rule('h6', 'health', 'shop apotheke', false),

  // Utilities
  rule('u1', 'utilities', 'strom', false),
  rule('u2', 'utilities', 'gas ', false),
  rule('u3', 'utilities', 'wasser', false),
  rule('u4', 'utilities', 'stadtwerke', false),
  rule('u5', 'utilities', 'vattenfall', false),
  rule('u6', 'utilities', 'e.on', false),
  rule('u7', 'utilities', 'enbw', false),
  rule('u8', 'utilities', 'telekom', false),
  rule('u9', 'utilities', 'vodafone', false),
  rule('u10', 'utilities', 'o2 ', false),
  rule('u11', 'utilities', '1&1', false),
  rule('u12', 'utilities', 'congstar', false),
  rule('u13', 'utilities', 'pyur', false),
  rule('u14', 'utilities', 'rundfunk', false),
  rule('u15', 'utilities', 'beitragsservice', false),

  // Kids (before shopping so specialty stores win)
  rule('k1', 'kids', 'kindergarten', false),
  rule('k2', 'kids', 'kita ', false),
  rule('k3', 'kids', 'kita-', false),
  rule('k4', 'kids', 'hort ', false),
  rule('k5', 'kids', 'tagesmutter', false),
  rule('k6', 'kids', 'tagespflege', false),
  rule('k7', 'kids', 'elternbeitrag', false),
  rule('k8', 'kids', 'babymarkt', false),
  rule('k9', 'kids', 'baby-walz', false),
  rule('k10', 'kids', 'baby walz', false),
  rule('k11', 'kids', 'dm baby', false),
  rule('k12', 'kids', 'mytoys', false),
  rule('k13', 'kids', 'toys"r"us', false),
  rule('k14', 'kids', 'toys r us', false),
  rule('k15', 'kids', 'spielzeug', false),
  rule('k16', 'kids', 'smyths', false),
  rule('k17', 'kids', 'lego ', false),
  rule('k18', 'kids', 'legoland', false),
  rule('k19', 'kids', 'haba ', false),
  rule('k20', 'kids', 'name it', false),
  rule('k21', 'kids', 'c&a kids', false),
  rule('k22', 'kids', 'kids fashion', false),
  rule('k23', 'kids', 'kinderschuhe', false),
  rule('k24', 'kids', 'schule ', false),
  rule('k25', 'kids', 'schulgeld', false),
  rule('k26', 'kids', 'nachhilfe', false),

  // Travel (hotels, flights, booking platforms — before generic shopping)
  rule('tv1', 'travel', 'booking.com', false),
  rule('tv2', 'travel', 'booking com', false),
  rule('tv3', 'travel', 'airbnb', false),
  rule('tv4', 'travel', 'expedia', false),
  rule('tv5', 'travel', 'hotel', false),
  rule('tv6', 'travel', 'hostel', false),
  rule('tv7', 'travel', 'lufthansa', false),
  rule('tv8', 'travel', 'eurowings', false),
  rule('tv9', 'travel', 'ryanair', false),
  rule('tv10', 'travel', 'easyjet', false),
  rule('tv11', 'travel', 'wizz air', false),
  rule('tv12', 'travel', 'condor', false),
  rule('tv13', 'travel', 'emirates', false),
  rule('tv14', 'travel', 'airline', false),
  rule('tv15', 'travel', 'flug', false),
  rule('tv16', 'travel', 'flights', false),
  rule('tv17', 'travel', 'holidaycheck', false),
  rule('tv18', 'travel', 'check24 reisen', false),
  rule('tv19', 'travel', 'opodo', false),
  rule('tv20', 'travel', 'kayak', false),
  rule('tv21', 'travel', 'sixt', false),
  rule('tv22', 'travel', 'hertz', false),
  rule('tv23', 'travel', 'europcar', false),
  rule('tv24', 'travel', 'mietwagen', false),
  rule('tv25', 'travel', 'rental car', false),
  rule('tv26', 'travel', 'ferry', false),
  rule('tv27', 'travel', 'fähre', false),
  rule('tv28', 'travel', 'urlaub', false),
  rule('tv29', 'travel', 'reisebüro', false),
  rule('tv30', 'travel', 'tui ', false),

  // Gifts (before generic shopping)
  rule('gf1', 'gifts', 'geschenk', false),
  rule('gf2', 'gifts', 'gift card', false),
  rule('gf3', 'gifts', 'gutschein', false),
  rule('gf4', 'gifts', 'blumen', false),
  rule('gf5', 'gifts', 'fleurop', false),
  rule('gf6', 'gifts', 'bloomon', false),
  rule('gf7', 'gifts', 'hallmark', false),
  rule('gf8', 'gifts', 'mytoys geschenk', false),

  // Hobbies (sports, music, crafts — before generic shopping)
  rule('hb1', 'hobbies', 'decathlon', false),
  rule('hb2', 'hobbies', 'intersport', false),
  rule('hb3', 'hobbies', 'sportcheck', false),
  rule('hb4', 'hobbies', 'bergfreunde', false),
  rule('hb5', 'hobbies', 'bike components', false),
  rule('hb6', 'hobbies', 'fahrrad', false),
  rule('hb7', 'hobbies', 'thomann', false),
  rule('hb8', 'hobbies', 'music store', false),
  rule('hb9', 'hobbies', 'musikhaus', false),
  rule('hb10', 'hobbies', 'fotofachhandel', false),
  rule('hb11', 'hobbies', 'calumet', false),
  rule('hb12', 'hobbies', 'basteln', false),
  rule('hb13', 'hobbies', 'hobby', false),
  rule('hb14', 'hobbies', 'modellbau', false),
  rule('hb15', 'hobbies', 'angelgeschäft', false),
  rule('hb16', 'hobbies', 'klettern', false),
  rule('hb17', 'hobbies', 'boulder', false),

  // Shopping / general retail
  rule('sh1', 'shopping', 'amazon', false),
  rule('sh2', 'shopping', 'ikea', false),
  rule('sh3', 'shopping', 'media markt', false),
  rule('sh4', 'shopping', 'saturn', false),
  rule('sh5', 'shopping', 'otto', false),
  rule('sh6', 'shopping', 'ebay', false),
  rule('sh7', 'shopping', 'klarna', false),
  rule('sh8', 'shopping', 'paypal', false),

  // Entertainment
  rule('e1', 'entertainment', 'cinema', false),
  rule('e2', 'entertainment', 'kino', false),
  rule('e3', 'entertainment', 'ticket', false),
  rule('e4', 'entertainment', 'eventim', false),
  rule('e5', 'entertainment', 'steam', false),
  rule('e6', 'entertainment', 'playstation', false),
  rule('e7', 'entertainment', 'xbox', false),

  // ATM
  rule('a1', 'atm', 'geldautomat', false),
  rule('a2', 'atm', 'bargeldauszahlung', false),
  rule('a3', 'atm', 'cash withdrawal', false),
  rule('a4', 'atm', 'ga auszahlung', false),
]
